parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true 

    App\:
        resource: '../src/'
        exclude: 
            - '../src/Kernel.php'
            - '../src/SalesDelivery/Infrastructure/ForTests/**/*'

    App\SalesDelivery\Application\Ports\Services\IAuthenticatedUserProvider: '@App\SalesDelivery\Infrastructure\ForProduction\Services\WebAuthenticatedUserProvider'
    App\SalesDelivery\Application\Ports\Services\IIdProvider: '@App\SalesDelivery\Infrastructure\ForProduction\Services\RandomIdProvider'
    App\SalesDelivery\Domain\Service\IPricingProvider: '@App\SalesDelivery\Infrastructure\ForProduction\Services\FixedPricingProvider'
    App\SalesDelivery\Application\Ports\Repositories\ICustomerRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlCustomerRepository'
    App\SalesDelivery\Application\Ports\Repositories\ICustomerOrderRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlCustomerOrderRepository'
    App\SalesDelivery\Application\Ports\Repositories\IDepositRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlDepositRepository'
    App\SalesDelivery\Application\Ports\Repositories\IUserRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlUserRepository'
    App\SalesDelivery\Application\Ports\Repositories\IOrderPaymentRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlOrderPaymentRepository'
    App\SalesDelivery\Application\Ports\Repositories\IDriverRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlDriverRepository'
    App\SalesDelivery\Application\Ports\Repositories\IVehicleRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlVehicleRepository'
    App\SalesDelivery\Application\Ports\Repositories\ICustomerDeliveryRepository: '@App\SalesDelivery\Infrastructure\ForProduction\Repository\SqlCustomerDeliveryRepository'

    App\SalesDelivery\Application\Listeners\ExceptionListener:
        tags: [ kernel.event_listener ]

